jQuery(document).ready(function($) {
    $('#load-more-posts').click(function() {
        var button = $(this),
            data = {
                'action': 'load_more_posts',
                'query': my_ajax_object.query_vars, 
                'page': button.data('page')
            };
    
        $.ajax({
            url: my_ajax_object.ajax_url,
            data: data,
            type: 'POST',
            beforeSend: function(xhr) {
                button.html('<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" style="margin: auto; background: rgba(255, 255, 255, 0); display: block; shape-rendering: auto;" width="50px" height="80px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid"><path d="M10 50A40 40 0 0 0 90 50A40 42 0 0 1 10 50" fill="#ffffff" stroke="none"><animateTransform attributeName="transform" type="rotate" dur="1s" repeatCount="indefinite" keyTimes="0;1" values="0 50 51;360 50 51"/></path><!-- [ldio] generated by https://loading.io/ --></svg>');
            },
            success: function(response) {
                console.log(response);
                if(response.content) {
                    $('.latest-posts').append(response.content);
                    button.data('page', response.next_page);
    
                    if (response.next_page >= response.max_page) {
                        button.remove();
                    } else {
                        $('.latest-posts').append(button);
                        button.text('More Articles');
                    }
                } else {
                    button.remove();
                }
            }
        });
    });    
});
